[workspace]
resolver = "2"
members = ["crates/core", "crates/relay", "crates/client", "crates/agent", "crates/mnr"]
exclude = ["crates/core/fuzz"]

[workspace.package]
version = "0.1.4"
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/mnrnetwork/mnr"
rust-version = "1.85"

[workspace.lints.clippy]
all = "warn"

[profile.release]
lto = "thin"
codegen-units = 1
